name: Export APK using Precompiled Shinobu Godot 4

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Project Heartbeat
        uses: actions/checkout@v4

      - name: 📥 Download Precompiled Shinobu Engine
        run: |
          wget https://github.com/EIRTeam/shinobu/releases/download/latest/engine.zip -O engine.zip
          unzip engine.zip
          chmod +x godot*

      - name: 📦 Download Android Export Templates (Godot 4.4.1)
        run: |
          mkdir -p ~/.local/share/godot/templates/4.4.stable
          wget https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz -O template.tpz
          tar -xf template.tpz -C ~/.local/share/godot/templates/4.4.stable

      - name: ⚙️ Set Up Godot Editor Settings
        run: |
          mkdir -p ~/.config/godot && mkdir -p $HOME/android-sdk
          cat <<EOF > ~/.config/godot/editor_settings-4.tres
          [gd_resource type="EditorSettings" format=3]
          export/android/android_sdk_path = "$HOME/android-sdk"
          export/android/debug_keystore = "$HOME/android-sdk/debug.keystore"
          EOF

      - name: 🔐 Generate Android Debug Keystore
        run: |
          keytool -genkey -v -keystore $HOME/android-sdk/debug.keystore \
            -storepass android -alias androiddebugkey -keypass android \
            -dname "CN=Android Debug,O=Android,C=US" \
            -keyalg RSA -keysize 2048 -validity 10000

      - name: 📲 Export Android APK
        run: |
          ./godot* --headless --path . --export-release "Android" build.apk

      - name: 📤 Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Project-Heartbeat-Shinobu-APK
          path: build.apk
